const api = require('@forge/api');
const { ConfluencePageResult, ApiError } = require('../models');

/**
 * Confluence Integration Service
 * Handles saving captured knowledge to Confluence pages
 */

/**
 * Save captured knowledge to Confluence
 * @param {Object} req - Forge request object containing title and content
 * @returns {Promise<ConfluencePageResult>} Result of page creation
 */
async function saveToConfluence(req) {
  try {
    const { title, content } = req.payload;
    
    // Validate inputs
    if (!title || !content) {
      throw new ApiError({
        code: 'INVALID_INPUT',
        message: 'Title and content are required'
      });
    }

    console.log(`Creating Confluence page: "${title}"`);
    
    // Validate permissions first
    const hasPermissions = await validatePermissions();
    if (!hasPermissions) {
      throw new ApiError({
        code: 'PERMISSION_DENIED',
        message: 'Insufficient permissions to create Confluence pages'
      });
    }

    // Format content for Confluence
    const formattedContent = formatContent(title, content);
    
    // Create the Confluence page
    const pageData = {
      type: 'page',
      title: title,
      space: {
        key: 'KNOWLEDGE' // Default space, could be configurable
      },
      body: {
        storage: {
          value: formattedContent,
          representation: 'storage'
        }
      }
    };

    const response = await api.asUser().requestConfluence('/wiki/rest/api/content', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(pageData)
    });

    if (response.status === 200 || response.status === 201) {
      const pageUrl = buildPageUrl(response.data);
      
      console.log(`✅ Confluence page created successfully: ${pageUrl}`);
      
      return new ConfluencePageResult({
        success: true,
        pageUrl: pageUrl,
        pageId: response.data.id
      });
    } else {
      throw new ApiError({
        code: 'CONFLUENCE_API_ERROR',
        message: `Failed to create page: ${response.status}`,
        details: response.data
      });
    }

  } catch (error) {
    console.error('Error creating Confluence page:', error.message);
    
    // Handle specific error types gracefully
    if (error.code === 'PERMISSION_DENIED' || error.message.includes('403')) {
      return new ConfluencePageResult({
        success: false,
        error: 'Permission denied. Please check your Confluence access permissions.'
      });
    }
    
    if (error.code === 'INVALID_INPUT') {
      return new ConfluencePageResult({
        success: false,
        error: error.message
      });
    }
    
    // Generic error handling
    return new ConfluencePageResult({
      success: false,
      error: `Failed to create Confluence page: ${error.message}`
    });
  }
}

/**
 * Validate that the user has permissions to create Confluence pages
 * @returns {Promise<boolean>} True if user has permissions
 */
async function validatePermissions() {
  try {
    // Try to get user info to validate permissions
    const response = await api.asUser().requestConfluence('/wiki/rest/api/user/current');
    return response.status === 200;
  } catch (error) {
    console.warn('Permission validation failed:', error.message);
    return false;
  }
}

/**
 * Format content for Confluence storage format
 * @param {string} title - Page title
 * @param {string} content - Raw content
 * @returns {string} Formatted content in Confluence storage format
 */
function formatContent(title, content) {
  // Convert plain text to Confluence storage format
  const timestamp = new Date().toISOString();
  
  const formattedContent = `
<h1>Knowledge Capture Session</h1>
<p><strong>Captured:</strong> ${timestamp}</p>
<p><strong>Title:</strong> ${title}</p>

<h2>Content</h2>
<div class="content-wrapper">
${formatTextToHtml(content)}
</div>

<h2>Metadata</h2>
<p><em>This page was automatically generated by the Institutional Memory Archaeologist.</em></p>
<p><strong>Source:</strong> Knowledge extraction interview</p>
<p><strong>Status:</strong> Requires review and organization</p>
`;

  return formattedContent;
}

/**
 * Convert plain text to basic HTML for Confluence
 * @param {string} text - Plain text content
 * @returns {string} HTML formatted text
 */
function formatTextToHtml(text) {
  if (!text) return '<p>No content provided.</p>';
  
  // Basic text formatting
  return text
    .split('\n\n') // Split paragraphs
    .map(paragraph => {
      if (paragraph.trim().length === 0) return '';
      
      // Handle bullet points
      if (paragraph.includes('•') || paragraph.includes('-')) {
        const items = paragraph.split('\n')
          .filter(line => line.trim().length > 0)
          .map(line => `<li>${escapeHtml(line.replace(/^[•\-]\s*/, ''))}</li>`)
          .join('');
        return `<ul>${items}</ul>`;
      }
      
      // Regular paragraph
      return `<p>${escapeHtml(paragraph.trim())}</p>`;
    })
    .filter(p => p.length > 0)
    .join('\n');
}

/**
 * Escape HTML characters
 * @param {string} text - Text to escape
 * @returns {string} Escaped text
 */
function escapeHtml(text) {
  const htmlEscapes = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#x27;'
  };
  
  return text.replace(/[&<>"']/g, (match) => htmlEscapes[match]);
}

/**
 * Build the full page URL from Confluence API response
 * @param {Object} pageData - Confluence page data from API
 * @returns {string} Full page URL
 */
function buildPageUrl(pageData) {
  if (pageData._links && pageData._links.webui) {
    // Use the webui link if available
    return `https://your-domain.atlassian.net/wiki${pageData._links.webui}`;
  }
  
  // Fallback URL construction
  const spaceKey = pageData.space ? pageData.space.key : 'KNOWLEDGE';
  return `https://your-domain.atlassian.net/wiki/spaces/${spaceKey}/pages/${pageData.id}`;
}

/**
 * Format knowledge artifact for Confluence storage
 * @param {Object} knowledgeArtifact - Knowledge artifact to format
 * @returns {string} Formatted content
 */
function formatKnowledgeArtifact(knowledgeArtifact) {
  const {
    title,
    content,
    tags = [],
    extractedAt,
    confidence,
    relatedTickets = [],
    employeeId
  } = knowledgeArtifact;

  const formattedContent = `
<h1>${escapeHtml(title)}</h1>

<div class="metadata-panel">
<h2>Metadata</h2>
<p><strong>Employee ID:</strong> ${escapeHtml(employeeId)}</p>
<p><strong>Extracted:</strong> ${new Date(extractedAt).toLocaleString()}</p>
<p><strong>Confidence Level:</strong> ${Math.round(confidence * 100)}%</p>
${tags.length > 0 ? `<p><strong>Tags:</strong> ${tags.map(tag => escapeHtml(tag)).join(', ')}</p>` : ''}
${relatedTickets.length > 0 ? `<p><strong>Related Tickets:</strong> ${relatedTickets.join(', ')}</p>` : ''}
</div>

<h2>Knowledge Content</h2>
<div class="knowledge-content">
${formatTextToHtml(content)}
</div>

<div class="footer">
<p><em>This knowledge was captured using the Institutional Memory Archaeologist during an offboarding interview.</em></p>
</div>
`;

  return formattedContent;
}

module.exports = {
  saveToConfluence,
  validatePermissions,
  formatContent,
  formatTextToHtml,
  formatKnowledgeArtifact,
  buildPageUrl,
  escapeHtml
};